### ISSUE TITLE
Naming consistency in nbList

### ISSUE THREAD

**Issue by jaketanderson** [deepmodeling/DMFF#78]
When creating neighbor lists, there is inconsistency on which keyword is used for the cutoff distance.

https://github.com/deepmodeling/DMFF/blob/2690192df36d393346be219e74b02bc4aa385d01/dmff/common/nblist.py#L11-L20
https://github.com/deepmodeling/DMFF/blob/2690192df36d393346be219e74b02bc4aa385d01/dmff/common/nblist.py#L113-L119

In these pieces of code we see `r_cutoff`, `r_cut`, and `rc`. I recommend these be standardized so that issues don't pop up due to confusion. The classical demo notebook, for example, specified `rc=4` as an argument to `NeighborList` but `NeighborList` takes no argument `rc`, only `r_cutoff`. I fixed that issue in PR #77.

**Comment by Ericwang6** [comment]
Hi @jaketanderson , thanks for your suggestion and appreciate the fix in demo!
