### ISSUE TITLE
[Feature Request] QEQ model’s parameterization for conductive electrodes with DMFF

### ISSUE THREAD

**Issue by gust-07** [deepmodeling/DMFF#89]
### Summary

1. QEq(Charge Equalization) model

-     electrostatic energy experession:
![image](https://user-images.githubusercontent.com/100009402/221860371-b1a35bae-47f0-483d-9d96-bc551608a763.png)

  the parameters X and H describe the  electronegativity and hardness of each atomic species.

-     constant charge constraint:
![image](https://user-images.githubusercontent.com/100009402/221860452-92af2c2f-cc48-49dd-ac5f-1a223f2703fb.png)

-     constant potential constraint:
![image](https://user-images.githubusercontent.com/100009402/221860498-07052dc5-b93e-4a3b-87ad-3caf20754209.png)

2. parameter optimization

-     the charge distribution should be similar to the results from ab inito calculation(DFT):
    
![image](https://user-images.githubusercontent.com/100009402/221860593-60c1026a-5f89-46ef-9b33-fca7cec00660.png)

-     use Lagrange mutiplier method to fullfill the constraints, CONP or CONQ.

### Motivation

Obtain energy functional expression.

- PME is able to calculate the coulombic interaction energy, the second part of the electrostatic energy, but  it's based on point charge model, and what wo want to do is gaussian charge model, there are many similarities.

-  the parameters X and H for different atomic types are unknown, we can use DMFF to learn these parameters.

### Suggested Solutions

- Energy kernal:based on the long-range interaction part energy of Ewald method.

![image](https://user-images.githubusercontent.com/100009402/222030309-e2999b79-f23e-4149-bcb5-1874e50916a0.png)

- Differentiable implementation ：Jaxopt + jit 

Any suggestions and comments on this solution are welcomed !

### Further Information, Files, and Links

1.Thomas-Fermi model :J. Chem. Phys. 153, 174704 (2020); https://doi.org/10.1063/5.0028232
2.Fully-Periodic CPM MD:J. Chem. Phys. 156, 184101 (2022); https://doi.org/10.1063/5.0086986

**Comment by WangXinyan940** [comment]
Thanks to the contribution of @gust-07 , the QEQ model has been published in our 1.0.0 release as one of the most important features. This issue would be closed.
